crud_pro/urls.py
from django.contrib import admin
from django.urls import path
from crud_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main,name='main'),
    path('home', views.home , name="home"),
    path('add_blog', views.add_blog , name="add_blog"),
    path('registration', views.register , name="registeration"),
    path('showdata', views.showdata , name="showdata"),
    path('update<int:id>', views.update , name="update"),
    path('detele<int:id>', views.delete , name="delete"),
    path('search', views.search, name ='search'),
    path('todo', views.TodoList, name ='Todo'),
    path('deletetodo<int:id>', views.Deletetodo , name="deletetodo"),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),



]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

crud_app/models.py
from django.db import models

# Create your models here.

class Detail(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    phone = models.BigIntegerField()
    address = models.TextField(max_length=150)
    rtime = models.DateTimeField(auto_now_add=True)
    dob = models.DateField(null=True)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=40)
    img = models.ImageField(upload_to = 'images')
    desc = models.TextField(max_length=10000)
    upload_by = models.CharField(max_length=40)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Todo(models.Model):
    item = models.CharField(max_length=1000)

    def __str__(self):
        return self.item

crud_app/forms.py
from django import forms
from .models import Detail , Blog
from django.forms.widgets import TextInput,EmailInput,NumberInput,Textarea

class DateInput(forms.DateInput):
    input_type = "date"

class Detail_form(forms.ModelForm):
    class Meta:
        model = Detail
        fields = "__all__"

        widgets = {
            'name' : TextInput(attrs={'placeholder' : 'Enter Your Name'}),
            'email' : EmailInput(attrs={'placeholder' : 'Enter Your Email address'}),
            'phone' : NumberInput(attrs={'placeholder' : 'Enter Your Phone Number'}),
            'address': TextInput(attrs={'placeholder': 'Enter Your Address'}),
            'dob': DateInput(),
        }

class Blog_form(forms.ModelForm):
    class Meta:
        model = Blog
        fields = "__all__"

        widgets = {
            'title' : TextInput(attrs={'placeholder' : 'Enter Your Title'}),
            'desc' : Textarea(attrs={'placeholder' : 'Descripion'}),
            'upload_by': TextInput(attrs={'placeholder': 'Enter Your Name'}),
        }

crud_app/views.py
from django.shortcuts import redirect, render
from crud_app.forms import Detail_form , Blog_form
from .models import Detail , Blog , Todo
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def main(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username already exists')
                return redirect('main')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'Email already exists')
                return redirect('main')

            else:
                user = User.objects.create_user(first_name=first_name,last_name=last_name,username=username,email=email,password=password)
                user.save()
                return redirect('main')
        else:
            messages.info(request,'Try Matching Password')
            return redirect('main')
    else:
        return render(request,'main.html')

def login(request):
    if request.method == "POST":
        username = request.POST['lusername']
        password = request.POST['lpassword']

        user = auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
            auth.login(request,user)
            return redirect('home')
        else:
            messages.info(request,'Invalid username/password')
            return redirect('login')     
    else:
        return render(request,'main.html') 

def logout(request):
    auth.logout(request)
    return redirect('main')

@login_required(login_url='login')
def home(request):
    data_list = Blog.objects.get_queryset().order_by('id')
    
    page = request.GET.get('page', 1)
    paginator = Paginator(data_list,2)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    return render(request,'home.html',{'data':data})
    

def add_blog(request):
    if request.method == 'GET':
        form = Blog_form()
        return render (request,'blogform.html',{'form':form})

    else:
        form = Blog_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')

def register(request):
    if request.method == 'GET':
        form = Detail_form()

        return render (request,'registerform.html',{'form':form})

    else:
        form = Detail_form(request.POST)
        print(form)
        if form.is_valid():
            form.save()

            return redirect('registeration')

def showdata(request):
    data = Detail.objects.all()
    return render (request,'showdata.html',{'data':data})

def update(request,id):
    if request.method == "GET":
        s = Detail.objects.get(id=id)
        form = Detail_form(instance=s)
        return render(request,'updatedata.html',{'s':form})
    else:
        s = Detail.objects.get(id=id)
        form = Detail_form(request.POST,instance=s)
        if form.is_valid():
            form.save()
            return redirect('showdata')

def delete(request,id):
    deletedata = Detail.objects.get(id=id)
    deletedata.delete()

    return redirect('showdata')

def search(request):
        searchinp = request.POST['search']
        data = Detail.objects.filter(name__contains=searchinp)
        return render(request,'showdata.html',{'data':data})


def TodoList(request):
    if request.method == 'POST':
        data = request.POST['todo']
        s = Todo(item=data)
        s.save()
        return redirect('Todo')

    else:
        tododata = Todo.objects.all()
        return render(request,'todolist.html',{'data':tododata})

def Deletetodo(request,id):
    tododata = Todo.objects.get(id=id)
    tododata.delete()
    return redirect('Todo')

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

</head>
<style>
  nav {
    backdrop-filter: blur(15px);
    box-shadow: 10px 10px 40px black;
  }
</style>

<body>
  <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="/home">Home</a>
      {% else %}
      <a class="navbar-brand" href="/">Home</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/home">Blogs</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="/registration">Register Yourself</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'showdata' %}">View Registrations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/todo">Todo List</a>
          </li>
        </ul>
      </div>
      {% if user.is_authenticated %}
      <b>Welcome Mr. {{user.first_name}}</b>&nbsp;&nbsp;
          <a href="{% url 'logout' %}" class="btn btn-danger">Signout</a>&nbsp;&nbsp;  
          <a href="/add_blog" class="btn btn-dark">Add Blog</a>
        {% endif %}
    </nav>
  </header>
  {% block content %}

  {% endblock %}
  <footer class="py-3 my-4">
    <p class="text-center text-muted">©2022 KunaL</p>
  </footer>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous">
  </script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% endblock %}

templates/blogform.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<title>Add New Blog</title>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        background: url("https://images.unsplash.com/photo-1589306962951-b3da28bfdfac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80");
        background-size: cover;
        background-repeat: no-repeat;
    }

    .container {
        box-shadow: 5px 5px 10px 10px rgba(0, 0, 0, 0.295);
        border-radius: 10px;
        padding: 50px;
        margin: 5% auto;
        backdrop-filter: blur(7px);
    }

    h1.text-center {

        font-size: 80px;
    }

    textarea#id_desc {
        height: 115px;
    }

    .size {
        font-size: 20px;
    }
</style>
<br><br>
<h1 class="text-center text-monospace">Add Blog</h1>
<div class="container">
    <form class="form-group size" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {{form.title|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form.img|as_crispy_field}}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                {{form.desc|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form.upload_by|as_crispy_field}}
                <button class="btn btn-dark" type="submit">Add Blog</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>Blog</title>
<style>
  * {
    box-sizing: border-box;
  }

  table {
    box-shadow: -5px 5px 15px 5px rgba(192, 152, 152, 0.2);
    border-radius: 50px;
  }

  body {
    background: url("{% static '/images/homebg2.jpg' %}");
    background-size: cover;
    background-repeat: no-repeat;
  }

  .pagination {
    background-color: transparent;
    border-radius: 10px;
    margin: auto;
    display: inline-flex;
    letter-spacing: 5px;
    font-size: 25px;
  }


  .container {
    background-color: rgb(0 0 0 / 70%);
    color: rgb(0, 0, 0);
    text-transform: inherit;

  }

  #desc {
    font-size: large;
  }

  #blog {
    box-shadow: 5px 5px 10px 10px rgba(0, 0, 0, 0.295);
    border-radius: 10px;
    padding: 50px;
    backdrop-filter: blur(10px);
    margin: 40px auto;
  }

  h1.text-center.text-monospace {
    font-size: 80px;
    background: black;
        color: white;
        padding: 50px;
  }
  p{
    font-size: 20px;
  }

</style>
<div class="background ">

  <!-- <table class="table table-borderless table-active">
            <thead></thead>
<tbody class="text-light">
    
    {% for i in data %}
    <tr>
        <td><h2><b>{{i.title}}</b></h2></td>
    </tr>
    <tr>
        <td><img src="{{i.img.url}}" style="max-width: 500px;"></td>
    </tr>
    <tr>
        <td><b><div id="desc"> Description - </div><p class="text-justify my-2">{{i.desc}}</p></b></td>
    </tr>
    <tr>
        <td>Upload by - <b>{{i.upload_by}} on {{i.time}}</b></td>
    </tr>
    <tr><td><hr></td></tr>
    {% endfor %}
</tbody>
</table> -->
  <h1 class="text-center text-monospace" style="text-shadow: 2px 2px 4px #000000;">Blogs</h1>
  <div class="container blog text-center bg-transparent" id="blog">
    {% for j in data %}
    <div class="row ">
      <div class="col-md-4"><br><br>
        <h2>{{j.title}}</h2>
        <img src="{{j.img.url}}" style="width: 100%;">
      </div>
      <div class="col-md-8 text-justify ">
        <br><br>
        <h3> Description -</h3><p>{{j.desc}}</p>
        Upload by - <b>{{j.upload_by}} on {{j.time}}</b>
        <hr>
      </div>
    </div>
    {% endfor %}
    {% if data.has_other_pages %}
    <ul class="pagination text-dark">
      {% if data.has_previous %}
      <li><a href="?page={{ data.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in data.paginator.page_range %}
      {% if data.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if data.has_next %}
      <li><a href="?page={{ data.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
    {% endif %}
  </div>


</div>



{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>Project | Home</title>
<style>
    section.s1 {
        background: black;
        color: white;
        padding: 50px;
    }

    p.text-justify {
        margin: 20PX 0; 
    }
    body {
        background: url('https://images.unsplash.com/photo-1634655377962-e6e7b446e7e9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80');
        background-size: cover;
        background-repeat: no-repeat;
        backdrop-filter: blur(15px);
  }

button.btn.btn-success {
    display: table;
    margin: auto;
}
span {
    display: table;
    margin: auto;
}

button.btn.btn-primary {
    display: table;
    margin: auto;
}
.container.c2 {
    padding: 40px;
}
h2.signup{
    margin: 20px auto;
    display: table;
    font-size: 4rem;
}
input.form-control.f1 {
    width: 70%;
    display: table;
    margin: auto;
}
label.f1{
    display: table;
    margin: auto;
}
.binfo{
    display: table;
    margin: auto;
}
h2.aboutblog{
    display: table;
    margin: 20px auto;
}
img{
    width: 80%;
    display: table;
    margin: auto;
}
section.aboutblog {
    margin: 65px;
}
img.binfo{
    width: 80%;
}
</style>
{% for msg in messages %}
<div class="alert alert-danger" role="alert">
    {{msg}}
    {% endfor %}
  </div>
<section class="s1">
    <div class="container">
        <div class="row">
            <div class="col-md-6 binfo">
                <!-- <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe nam omnis,
                    voluptatum itaque cum quibusdam perferendis repellat, a expedita dolorem, iusto ad voluptatibus? Id,
                    commodi enim? Maxime quam dolorem, at nemo alias maiores, iure, eius inventore cupiditate
                    accusantium ipsum repellendus possimus aliquid officia consequuntur saepe.</p> -->
                    <img class="binfo" src="{% static '/images/bloginfo.jpg' %}" alt="">
            </div>
            <div class="col-md-6 f1">
                <h3 class="text-center">Please Sign In to continue!</h3>
                <form class="form-group" method="POST" action="{% url 'login' %}">
                    {% csrf_token %}
                    <label class="f1" for="username">Username</label>
                    <input type="text" name="lusername" id="" class="form-control f1" >
                    <label class="f1" for="Password">Password</label>
                    <input type="password" name="lpassword" id="" class="form-control f1" ><br>
                    <button type="submit" class="btn btn-success" >Sign in</button>
                </form>
                <span>
                    Don't Have Account<a href="#signup"> Click Here!</a>
                </span>
            </div>
        </div>
    </div>
</section>
<section class="aboutblog">
    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <h2 class="aboutblog">What is Blog?</h2>
                <p class="text-justify">A blog (a shortened version of “weblog”) is an online journal or informational website displaying information in reverse chronological order, with the latest posts appearing first, at the top. It is a platform where a writer or a group of writers share their views on an individual subject.</p>
            </div>
            <div class="col-md-6">
                <img src="{% static '/images/blogimg.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<section class="s2" id="signup">
    <h2 class="signup">Signup Here</h2>
        <div class="container c2">
<form method="post" action="{% url 'main' %}">
    {% csrf_token %}
    <div class="row">
<div class="col-md-6">
    <div class="form-group">
        <label class="f2" >First Name</label>
        <input type="text" class="form-control" name="first_name">
    </div>
  </div>
<div class="col-md-6">
    <div class="form-group">
        <label class="f2">Last Name</label>
        <input type="text" class="form-control" name="last_name">
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="f2" >UserName</label>
            <input type="text" class="form-control" name="username">
        </div>
        </div>
<div class="col-md-6">
    <div class="form-group">
        <label class="f2" >Email address</label>
        <input type="email" class="form-control" name="email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
</div>
    </div>
    <div class="row">
        <div class="col-md-6">

            
            <div class="form-group">
                <label class="f2" for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="password">
            </div>
        </div>
<div class="col-md-6">

    
    <div class="form-group">
        <label class="f2" for="exampleInputPassword1">Confirm Password</label>
        <input type="password" class="form-control" name="password2">
    </div>
</div>
</div>

<button type="submit" class="btn btn-primary" name="register">Register</button>
</form>
</div>

</section>

{% endblock %}

templates/registerform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Registration Form</title>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        background: url("https://images.unsplash.com/photo-1619252584172-a83a949b6efd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80");
        background-size: cover;
        background-repeat: no-repeat;
    }

    .boxshadow {
        box-shadow: 5px 5px 10px 10px rgba(0, 0, 0, 0.295);
        border-radius: 10px;
        backdrop-filter: blur(3px);
        font-size: 20px;
    }

    h1.text-center {
        font-size: 80px;
    }

    .container {
        margin: 5% auto;
    }

    button.btn.btn-dark {
        display: table;
        margin: auto;
    }

    form.form-group {
        padding: 50px;
    }
</style>
<div class="container">
    <h1 class="text-center text-monospace">Registration Form</h1>
    <br>
    <div class="boxshadow">
        <form class="form-group" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{form.name|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.email|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{form.phone|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.dob|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {{form.address|as_crispy_field}}
                </div>
            </div>
            <button class="btn btn-dark" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/showdata.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<title>Data</title>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        background: url("{% static '/images/showbg.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }

    .container {
        margin: 5% auto;
    }

    h1.text-center.text-monospace {
        box-shadow: 5px 5px 10px 10px rgb(0 0 0 / 30%);
        border-radius: 10px;
        font-size: 80px;
        backdrop-filter: blur(5px);
        width: 48%;
        display: table;
        margin: auto;
    }

    button.btn.btn-dark {
        display: table;
        margin: 10px auto;
    }

    form.form-group {
        width: 40%;
        margin: 28px auto;
    }

    table.table.table-striped.table-light.bg-borderless {
        display: table;
        margin: auto auto;
    }
</style>
<div class="container">
    <h1 class="text-center text-monospace ">Registrations</h1>
    <form class="form-group" method="post" action="{% url 'search' %}">
        {% csrf_token %}
        <div class="row">
            <input type="text" name="search" placeholder="Search Here" class="form-control" required style="text-align: center;
                    font-family: monospace;
                    font-style: italic;">
            <button type="submit" class="btn btn-dark">Search</button>
        </div>
    </form>
</div>
<div class="container">

    <table class="table table-striped table-light bg-borderless"
    style="box-shadow: 5px 5px 10px 10px rgba(0, 0, 0, 0.295);border-radius: 20px;text-shadow: 2px 2px 4px #ffffff;">
    <thead>
        <!-- <th>Id</th> -->
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th>D.O.B</th>
        <th>Date of Registration</th>
        <th colspan="2" class="text-center">Action</th>
    </thead>
    <tbody>
        {% for i in data %}
        <tr>
            <!-- <td>{{i.id}}</td> -->
            <td>{{i.name}}</td>
            <td>{{i.email}}</td>
            <td>{{i.phone}}</td>
            <td>{{i.address}}</td>
            <td>{{i.dob}}</td>
            <td>{{i.rtime}}</td>
            <td><a href="{% url 'update' i.id %}" class="btn btn-primary text-light">Modify</a> </td>
            <td><a href="{% url 'delete' i.id %}" class="btn btn-danger text-light">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>


{% endblock %}

templates/todolist.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>Todo List</title>
<style>
    body {
        background: url("{% static '/images/todo.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }

    .container {
        margin: 5% auto;
    }

    input.form-control {
        width: 50%;
        display: table;
        margin: auto;
    }

    button.btn.btn-primary {
        display: table;
        margin: 15px auto;
    }


    table {
        box-shadow: 15px 17px 40px 0px #000000;
        border-radius: 20px;
        backdrop-filter: blur(3px);
    }

    h1.text-monospace {
        box-shadow: 5px 5px 10px 10px rgb(0 0 0 / 30%);
        border-radius: 10px;
        font-size: 80px;
        backdrop-filter: blur(10px);
        width: 36%;
        display: table;
        margin: auto;
    }

    form {
        margin: 20px;
    }
</style>

<section>
    <div class="container text-center">
        <h1 class="text-monospace">Todo List</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="todo" class="form-control" placeholder="Enter Item" required>
            <button type="submit" class="btn btn-primary">Add item</button>
        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>Todo</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr>
                    <td>{{i.item}}</td>
                    <td><a href="{% url 'deletetodo' i.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</section>

{% endblock %}

templates/updatedata.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Update Details</title>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        background: url("https://pixabay.com/get/g0cfb6df68a5899603ec127425d2aa02fc190c6a1caea729d23c6b828d1b9f35c75c468443be7a29e8545746492b24d110d5452f5d65c84d27ab98cae7b1d1a3e_1920.png");
        background-repeat: no-repeat;
    }

    .boxshadow {
        box-shadow: 5px 5px 10px 10px rgba(0, 0, 0, 0.295);
        border-radius: 10px;
        backdrop-filter: blur(3px);
        font-size: 20px;
    }

    h1.text-center {
        font-size: 80px;
    }

    .container {
        margin: 5% auto;
    }

    button.btn.btn-dark {
        display: table;
        margin: auto;
    }

    form.form-group {
        padding: 50px;
    }
</style>

<body>
    {% load crispy_forms_tags %}
    <br><br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
    <h1 class="text-center text-monospace">Update Details</h1>

    <div class="container boxshadow">
        <form class="form-group my-5" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    {{s.name|as_crispy_field}}
                </div>
                <div class="col-md-5">
                    {{s.email|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    {{s.phone|as_crispy_field}}
                    {{s.dob|as_crispy_field}}
                </div>
                <div class="col-md-5">
                    {{s.address|as_crispy_field}}
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-success btn-lg " type="submit">Submit</button>
            </div>
        </form>
        <hr>
    </div>

    {% endblock %}